version: '3'

services:
  client:
    build: ./my-app
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production


  db:
    image: postgres:13
    volumes:
      - ./TABLE.sql:/docker-entrypoint-initdb.d/TABLE.sql
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase